
	/* FILENAME : MDI.H	*/


	#define INIT_MENU_POS		0
	#define TEXT_MENU_POS		2
	#define GRAF_MENU_POS		1

	#define IDM_TEXT		10
	#define IDM_GRAPHICS		11
	#define IDM_EXIT		12
	#define IDM_CLOSE		13

	#define IDM_BLACK		20
	#define IDM_RED			21
	#define IDM_GREEN		22
	#define IDM_BLUE		23
	#define IDM_WHITE		24

	#define IDM_CASCADE		30
	#define IDM_TILE		31
	#define IDM_ARRANGEICON		32
	#define IDM_CLOSEALL		33

	#define ID_FIRSTCHILD		50

