
 /* ---- Colors.h --------------------------------------------------------- */
 /* This header file contains color definitions in text mode 				*/
 /* ----------------------------------------------------------------------- */


 #define	BRIGHT		0x08
 #define	FLASHING	0x80
 #define	BLACK		0x00
 #define	BLUE		0x01
 #define	GREEN		0x02
 #define	CYAN		0x03
 #define	RED			0x04
 #define	MAGENTA		0x05
 #define	YELLOW		0x06
 #define	WHITE		0x07
 #define	BACKGROUND	* 16
 #define	FOREGROUND	* 1
